config/routes.rb
Rails.application.routes.draw do
  root 'vote#index'
  get 'vote/index'  => 'vote#index'
  post 'vote/create' => 'vote#create'
  get 'vote/rankings' => 'vote#rankings'
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  image_data :string
#  bio        :text
#  job        :string
#  hobbies    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Profile < ApplicationRecord
    include ImageUploader::Attachment.new(:image)

    # First Name, Last Name, Profile Photo and Bio should not be empty
    validates :first_name, :last_name, :image_data, :bio, presence: true

    # Bio should not be greater than 300 characters
    validates :bio, length: { maximum: 300 }

    # Full Name
    def full_name
        (self.first_name + " " + self.last_name).strip
    end

    # Choose a random profile
    scope :random_profile, -> {
        # Set a random offset
        offset = rand(Profile.count)

        # Get the random Profile
        Profile.offset(offset).first
    }

    # Choose two different random profiles
    # def self.choose_two_random_profiles
    #     profile = {}
    #     profile[:left] = self.random_profile
    #     while(profile[:left]==profile[:right] || profile[:right].nil? )
    #         profile[:right] = self.random_profile
    #     end
    #     profile
    # end
    scope :choose_two_random_profiles, -> {
        profile = {}
        profile[:left] = self.random_profile
        while(profile[:left]==profile[:right] || profile[:right].nil? )
            profile[:right] = self.random_profile
        end
        profile
    }

    # Win Count
    def win_count
        Vote.where(winner_id: self.id).count(:winner_id)
    end

    # Lose Count
    def lose_count
        Vote.where(loser_id: self.id).count(:loser_id)
    end
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  winner_id  :integer
#  loser_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ApplicationRecord

    scope :rankings, -> {
        rankings = []

        Profile.all.each { |profile|
            profile = {
                :profile => profile,
                :points => profile.win_count - profile.lose_count
            }

            rankings << profile
        }

        rankings.sort_by! { |k| k[:points] }.reverse
    }

    # scope :winners, -> {
    #     select("votes.winner_id, count(votes.winner_id) as votes.win_count").
    #     group("votes.winner_id").
    #     order("count(votes.winner_id) DESC")
    # }

    # scope :losers, -> {
    #     group("votes.loser_id").
    #     order("count(votes.loser_id) DESC")
    # }

    # scope :top10, ->{
    #     joins(:vote).
    #     group("facts.id").
    #     order("count(votes.id) DESC").
    #     limit(10)
    # }

    # scope :top10, ->{
    #     select("songs.id, songs.name, artist_id, count(play_counts.id) AS play_count").
    #     joins(:play_count).
    #     joins(:artist).
    #     group("songs.id").
    #     order("play_count DESC").
    #     limit(10)
    #   }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :image, :bio, :job, :hobbies)
    end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  def index
    profiles = Profile.choose_two_random_profiles
    
    @profile_left = profiles[:left]
    @profile_right = profiles[:right]
  end

  # Create a Vote
  def create
    winner = params[:winner_id]
    loser = params[:loser_id]

    Vote.create(winner_id: winner, loser_id: loser)
    
    redirect_to vote_index_url
  end

  # Show Rankings
  def rankings
    # p Profile.find(1).win_count
    # p Profile.find(1).lose_count
    # p Vote.rankings
    @rankings = Vote.rankings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facesmash</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :profile_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :profile_last_name %>
  </div>

  <div class="field">
    <%= form.label :image %><br/>
    <%= form.file_field :image, id: :photo_image %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="field">
    <%= form.label :job %>
    <%= form.text_field :job, id: :profile_job %>
  </div>

  <div class="field">
    <%= form.label :hobbies %>
    <%= form.text_field :hobbies, id: :profile_hobbies %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div class="card" style="width: 20rem;">
<%= image_tag profile.image.url, class: 'img-fluid', width: 200, class: "card-img-top" %>
<div class="card-body">
    <h4 class="card-title"><%= profile.full_name %></h4>
    <p class="card-text"><%= profile.bio %></p>
    <p class="card-text"><strong>Job:</strong> <%= profile.job %></p>
    <p class="card-text"><strong>Hobbies:</strong> <%= profile.hobbies %></p>
    <%#= link_to button_tag('Edit',class:"btn btn-primary"), edit_profile_path(profile) %>
    <%#= link_to button_tag('Delete',class:"btn btn-primary"), profile, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<div class="row">
<% @profiles.each do |profile| %>
<div class="col">
  <div class="card" style="width: 20rem;">
    <%= image_tag profile.image.url, class: 'img-fluid', width: 200, class: "card-img-top" %>
    <div class="card-body">
      <h4 class="card-title"><%= profile.full_name %></h4>
      <p class="card-text"><%= profile.bio %></p>
      <p class="card-text"><strong>Job:</strong> <%= profile.job %></p>
      <p class="card-text"><strong>Hobbies:</strong> <%= profile.hobbies %></p>
      <%= link_to button_tag('Show',class:"btn btn-primary"), profile %>
      <%= link_to button_tag('Edit',class:"btn btn-primary"), edit_profile_path(profile) %>
      <%= link_to button_tag('Delete',class:"btn btn-primary"), profile, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>
<% end %>
</div>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Bio</th>
      <th>Job</th>
      <th>Hobbies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= image_tag profile.image.url, class: 'img-fluid', width: 200 %></td>
        <td><%= profile.full_name %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.job %></td>
        <td><%= profile.hobbies %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @profile %>

app/views/vote/index.html.erb
<h1>Facesmash</h1>
<p>Vote for a Person</p>

<div class="row">
    <div class="col-sm-6">
        <%= render @profile_left %>
        
        <%= form_with url: vote_create_path, method: :post do |f| %>
        <%= f.hidden_field :winner_id, value: @profile_left.id %>
        <%= f.hidden_field :loser_id, value: @profile_right.id %>
            <%= f.submit "Vote #{@profile_left.first_name}", class: 'btn btn-primary' %>
        <% end %>
    </div>


    <div class="col-sm-6">
        <%= render @profile_right %>

        <%= form_with url: vote_create_path, method: :post do |f| %>
        <%= f.hidden_field :winner_id, value: @profile_right.id %>
        <%= f.hidden_field :loser_id, value: @profile_left.id %>
            <%= f.submit "Vote #{@profile_right.first_name}", class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

<br>
<%= link_to 'View Rankings', vote_rankings_path, class: 'btn btn-success' %>

app/views/vote/rankings.html.erb
<h1>Rankings</h1>

<% @rankings.each_with_index do |ranking, index| %>
    <h2>#<%= index+1 %> <%= ranking[:profile].full_name %> - <%= pluralize(ranking[:points],'point') %></h2>
<% end %>

<%= link_to 'Back', root_path, class: 'btn btn-primary' %>